### ISSUE TITLE
Chapter 7 (Duck-typing)

### ISSUE THREAD

**Issue by wynand1004** [mattharrison/IllustratedPy3#9]
Due to duck-typing the type function is somewhat frowned
upon. - This could use some explaining.

**Comment by mattharrison** [comment]
Here's a duck typing writeup:

 Duck typing comes from a scene in *Monte Python and the Holy Grail*, where a lady
  is determined to be a witch because she weighs as much as a duck. (If this is
  confusing go watch the movie, I find it enjoyable). The idea is that because she had
  characteristics (her weight) that were the same as a duck's, she could be considered a witch.

  Python takes a similar approach. If I want to loop over an object, I simply put it
  in a ``for`` loop. I don't check first to see if it is a list, or a subclass of a list,
  I just loop over it. If I want to use a plus operation, I don't check to see if the object is a number,
  or string (or other type that supports addition). If the operation fails, that's ok, it is an
  indication that I'm not providing the correct type.

  If you are familiar with Object Oriented programming, duck typing eases the requirement
  for subclassing. Rather than inheriting multiple classes to take advantage of behaviors they
  provide, we just need to implement the protocols (usually by defining a method or two).
  For example, to create a class that adds, you just need to implement a ``__add__`` method.
  Any class can define that method and respond to the plus operation.

**Comment by wynand1004** [comment]
Much better - and quite interesting! 

PS. Monte -> Monty :)

**Comment by wdennis** [comment]
I thought "duck typing" was so-named because of the [definition I find on wikipedia.org](https://en.wikipedia.org/wiki/Duck_typing):

> using the principle, "If it walks like a duck and it quacks like a duck, then it must be a duck." 

(i.e., inferring the object type by its attributes and methods)

That said, I do remember the "witch scene" warmly :)

**Comment by mattharrison** [comment]
Updated (Aug14) thanks @wdennis
