### ISSUE TITLE
17.5 function (or variable) names

### ISSUE THREAD

**Issue by Rad-Prof** [mattharrison/IllustratedPy3#92]
I see that you are a proponent of function and variable names that are lowercase and use underscore for word separation.  When I learned Python (or maybe from where I learned Python), variable and function names like sectionList and hasTimeOverlap() were acceptable.  I'm guessing this isn't the case anymore.  Can you explain why?  Perhaps you have and I just missed it.  I confess I haven't read PEP 8 yet.

**Comment by mattharrison** [comment]
Added the following paragraph:


Languages such as Java have adopted the camelcase naming convention. In that
style you might have a variable named ``sectionList`` or a method named ``hasTimeOverlap``.
In Python we would typically name these ``section_list`` and ``has_time_overlap`` respectively.
While Python code should follow the PEP 8 conventions, there is also an allowance in PEP 8
for consistency. If the code you are working on has a different style of naming convention,
follow suit and be consistent with the existing code. Indeed, the ``unittest`` module in the
standard library still has Java style conventions (because it was originally a port from the
Java library junit).

**Comment by Rad-Prof** [comment]
Love it!
